[package]
name = "proto-build"
version = "0.1.0"
authors = ["zakir <zakir@pundix.com>"]
edition = "2018"


[dependencies]
prost = "0.6"
tonic = "0.3.1"
prost-build = "0.6"
tempdir = "0.3"
walkdir = "2"
tonic-build = "0.3.1"
