[package]
name = "proto-build"
version = "0.1.0"
authors = ["zakir <nash@wokoworks.com>"]
edition = "2018"


[dependencies]
prost = "0.9.0"
tonic = "0.6.2"
prost-build = "0.9.0"
tempdir = "0.3"
walkdir = "2"
tonic-build = "0.6.2"